from typing import Protocol, Optional
import pigpio

class PigpioProtocol(Protocol):
    def get_pi(self) -> pigpio.pi:...

    def get_pin_status(self, pin_id: int) -> bool:...

    def get_gpio_pin_status(self, gpio: Optional[int]) -> bool:...

    def get_gpio_status(self) -> dict[int, bool]:...