from typing import Protocol, Optional

from dto.motor_dto import MotorDto
from services.motor.tasks.task_protocol import SingleMotorTaskProtocol
from servomotor.dto.controller_status import EMotorStatus


class MotorServiceProtocol(Protocol):
    def is_calibration_enabled(self) -> bool:...

    def set_calibration(self, value: bool) -> bool:...

    def get_all(self) -> list[MotorDto]:...

    def get_by_id(self, motor_id: int) -> Optional[MotorDto]:...

    def update(self, motor_dto: MotorDto) -> MotorDto: ...

    def set_origin_all(self):...

    def set_origin(self, motor_id: int):...

    def set_limit_all(self):...

    def set_limit(self, motor_id: int):...

    def run_to_home(self, motor_id: int):...

    def run_to_origin(self, motor_id: int):...

    def run_steps(self, motor_id: int, steps: int = 1, forward: bool = True): ...

    def run_gcode(self, gcode: str):...

    def run(self, task: SingleMotorTaskProtocol):...

    def stop(self, ids: list[int]) -> None:...

