from typing import Protocol

from dto.motor_dto import MotorDto
from servomotor.controller.single_controller import SinglePWMController

from servomotor.dto.controller_status import EMotorStatus
from servomotor.dto.run_cmd_dto import ControllerRunDto


class ControllerServiceProtocol(Protocol):
    def start(self, controller_id: int, steps: int, freq_hz: int, forward: bool = True): ...

    def start_wave(self, run_cmd: list[ControllerRunDto], pulse_us: int = 5): ...

    def stop(self, controller_id: int):...

    def stop_all(self) -> None: ...

    def is_any_running(self) -> bool:...

    def is_running(self, motor_id: int) -> bool:...

    def set_home(self, motor_id: int):...

    def get_status(self, motor_id: int) -> EMotorStatus:...

    def get_position(self, motor_id: int) -> int:...
