from typing import Protocol

from dto.motor_dto import MotorDto
from servomotor.controller import ControllerPWM
from servomotor.controller_status import EMotorStatus


class ControllerProtocol(Protocol):
    def start_controller(self, controller_id: int, steps: int, freq_hz: int, forward: bool = True): ...

    def stop_controller(self, controller_id: int) -> bool:...

    def stop_all_controllers(self) -> None: ...

    def is_any_controller_running(self) -> bool:...

    def is_controller_running(self, motor_id: int) -> bool:...

    def set_controller_home(self, motor_id: int):...

    def get_controller_status(self, motor_id: int) -> EMotorStatus:...

    def get_controller_position(self, motor_id: int) -> int:...

    def update_controller(self, motor_dto: MotorDto) -> ControllerPWM:...