from enum import Enum


class AppServices(str, Enum):
    APP_DB= "APP_DB",
    APP_SOCKET="APP_SOCKET"
    APP_FLASK="APP_FLASK"

    MOTOR_DAO="MOTOR_DAO"
    PIN_DAO="PIN_DAO"

    MOTOR_SERVICE="MOTOR_SERVICE"
    PIN_SERVICE="PIN_SERVICE"
    PIGPIO_SERVICE="PIGPIO_SERVICE"

    MOTOR_EVENT_MANAGER="MOTOR_EVENT_MANAGER"
    PIN_EVENT_MANAGER="PIN_EVENT_MANAGER"
